In [10]:
import numpy as np

In [11]:
lista = [3, 2, 4, 1, 5, 3, 4, 8, 4]
vector = np.array(lista)

vector

array([3, 2, 4, 1, 5, 3, 4, 8, 4])

In [12]:
print(vector.size)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

9
(9,)
1
int32


In [13]:
print(vector[5])
print(vector[2:8])
print(vector[1:5:3])

3
[4 1 5 3 4 8]
[2 5]


In [14]:
print(vector.sum())
print(vector.mean())
print(vector.max())
print(vector.min())
print(vector.std())

34
3.7777777777777777
8
1
1.8724777273725242


In [27]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz.size)
print(matriz.mean())
print(matriz.std())
print(matriz.mean())

print(matriz)

9
5.0
2.581988897471611
5.0
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
for i in range(3):
    for j in range(3):
        print(matriz[i][j])

1
2
3
4
5
6
7
8
9
