In [1]:
import numpy as np

In [2]:
ceros = np.zeros(8)
unos = np.ones(5)
matrizIdentidad = np.eye(3)
aleatorio = np.random.rand(3,3)
print(ceros)
print(unos)
print(matrizIdentidad)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
cubo = np.array([[[2, 4, 6], [2, 4, 6], [2, 4, 6]],
                 [[2, 4, 6], [2, 4, 6], [2, 4, 6]],
                 [[2, 4, 6], [2, 4, 6], [2, 4, 6]]])

print(cubo)

cubo = np.ones((3, 3, 3))
print(cubo)

[[[2 4 6]
  [2 4 6]
  [2 4 6]]

 [[2 4 6]
  [2 4 6]
  [2 4 6]]

 [[2 4 6]
  [2 4 6]
  [2 4 6]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [4]:
vector1 = np.array([2,4,6])
vector2 = np.array([8,3,1])

sumavectores = vector1 + vector2

print(sumavectores)

[10  7  7]


In [5]:
matriz1 = np.array(([2,3],[4,5],[6,7]))

matriz2 = np.array(([8,9],[10,11],[12,13]))
resultado = matriz1 + matriz2

print(resultado)

[[10 12]
 [14 16]
 [18 20]]
